# Generated by Django 6.0.3 on 2026-04-02 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_album_song_delete_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['name']},
        ),
    ]
