# Generated by Django 6.0.3 on 2026-04-02 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_alter_song_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={},
        ),
    ]
